#include <iostream>
#include <random>

using namespace std;
 
int main()
{
    srand(999);
    random_device mydevice;  // Will be used to obtain a seed for the random number engine
    mt19937  gen(mydevice()); // Standard mersenne_twister_engine seeded with rd(), to generate pseudo random numbers
    uniform_int_distribution<> random_int(1, 100);
 
    // Use distrib to transform the random unsigned int
    // generated by gen into an int in [1, 6]
    for (int n = 0;  n != 6; ++n) cout << random_int(gen) << ' ';
    cout << '\n';
}
