#include <iostream>
#include <random>

using namespace std;
 
int main()
{
    random_device mydevice;  // Will be used to obtain a seed for the random number engine
    uniform_int_distribution<> random_int(1, 100);
 
    // Use distrib to transform the random unsigned int
    // generated by gen into an int in [1, 6]
    for (int n = 0;  n != 6; ++n) cout << random_int(mydevice) << ' ';
    cout << '\n';
}
