#include <iostream>
#include <random>

using namespace std;
 
int main()
{

    int seed=19937; // fixed random seed
    std::default_random_engine  mydevice(seed); //
    uniform_int_distribution<> random_int(1, 100);

    // Use distrib to transform the random unsigned int
    // generated by gen into an int in [1, 6]
    for (int n = 0;  n != 6; ++n) cout << random_int(mydevice) << ' ';
    cout << '\n';
}
